# hmc_traj.py
# Plots one leapfrog trajectory of the HMC sampler used in Example 6.5
# (see hmc_demo.py). The trajectory is generated by simulating L
# leapfrog steps with step size eps from a chosen starting point and
# deterministic momentum, then overlaid on the contours of the target
# density. The start and end points are labeled directly on the figure.
# The figure size and contour grid are matched to hmc_demo.py for
# visual consistency across the two panels of Figure 6.2.

import numpy as np
import matplotlib.pyplot as plt

# log target density and its gradient (same as hmc_demo.py)
logf = lambda q: -0.05*(q[1] - q[0]**2)**2 \
    - 0.5*(q[0] - 1)**2
grad_logf = lambda q: np.array([q[0]/5*(q[1] - q[0]**2)
    - (q[0] - 1), -(q[1] - q[0]**2)/10])

# trajectory settings: smaller step and longer chain than in hmc_demo
# are used here to produce a smoother visual path that traverses both
# sides of the high-density region
eps = 0.3
L = 20
theta0 = np.array([-2.0, 6.0])   # starting point above the high-density region
p0 = np.array([1.5, -2.0])       # momentum: rightward and downward

# simulate the trajectory, storing the position at every leapfrog step
traj = np.zeros((L+1, 2))
theta_t = theta0
p_t = p0
traj[0, :] = theta_t
g = grad_logf(theta_t)
p_t = p_t + 0.5*eps*g
for kk in range(1, L):
    theta_t = theta_t + eps*p_t
    g = grad_logf(theta_t)
    p_t = p_t + eps*g
    traj[kk, :] = theta_t
theta_t = theta_t + eps*p_t
traj[L, :] = theta_t

print('trajectory start:', traj[0, :], ' end:', np.round(traj[-1, :], 3))

# target density contours over a fixed range that approximates the
# typical sample range produced by hmc_demo.py, so that the contour
# lines line up visually across the two panels
xg = np.linspace(-2.5, 4.5, 300)
yg = np.linspace(-10, 19, 300)
T1, T2 = np.meshgrid(xg, yg)
Z = np.exp(-(0.05*(T2 - T1**2)**2 + 0.5*(T1 - 1)**2))
Z = Z/Z.max()

plt.figure(figsize=(4, 3))
plt.contour(T1, T2, Z, 12, colors='k', linewidths=0.5)
plt.plot(traj[:, 0], traj[:, 1], '-ok', markersize=4, linewidth=1.2)

# label start and end directly on the figure (no legend)
plt.text(traj[0, 0] + 0.2, traj[0, 1] + 1.5,
         'start', fontsize=14)
plt.text(traj[-1, 0] + 0.2, traj[-1, 1] + 1.5,
         'end', fontsize=14)

plt.xlabel(r'$\theta_1$', fontsize=14)
plt.ylabel(r'$\theta_2$', fontsize=14)
plt.tight_layout()
plt.show()
