% hmc_traj.m
% Plots one leapfrog trajectory of the HMC sampler used in Example 6.5
% (see hmc_demo.m). The trajectory is generated by simulating L
% leapfrog steps with step size eps from a chosen starting point and
% deterministic momentum, then overlaid on the contours of the target
% density. The start and end points are labeled directly on the figure.
% The figure size and contour grid are matched to hmc_demo.m for
% visual consistency across the two panels of Figure 6.2.

clear; close all;

% log target density and its gradient (same as hmc_demo.m)
logf = @(q) -0.05*(q(2) - q(1).^2).^2 ...
    - 0.5*(q(1) - 1).^2;
grad_logf = @(q) [q(1)/5*(q(2) - q(1).^2) ...
    - (q(1)-1); -(q(2) - q(1).^2)/10 ];

% trajectory settings: smaller step and longer chain than in hmc_demo
% are used here to produce a smoother visual path that traverses both
% sides of the high-density region
eps = 0.3; L = 20;
theta0 = [-2;  6];                   % starting point above the high-density region
p0     = [ 1.5; -2];                 % momentum: rightward and downward

% simulate the trajectory, storing the position at every leapfrog step
traj = zeros(L+1, 2);
theta_t = theta0; p_t = p0;
traj(1,:) = theta_t';
g = grad_logf(theta_t);
p_t = p_t + 0.5*eps*g;
for k = 1:L-1
    theta_t = theta_t + eps*p_t;
    g = grad_logf(theta_t);
    p_t = p_t + eps*g;
    traj(k+1,:) = theta_t';
end
theta_t = theta_t + eps*p_t;
traj(L+1,:) = theta_t';

% target density contours over a fixed range that approximates the
% typical sample range produced by hmc_demo.m, so that the contour
% lines line up visually across the two panels
xg = linspace(-2.5, 4.5, 300);
yg = linspace(-10, 19, 300);
[T1, T2] = meshgrid(xg, yg);
Z = exp(-(0.05*(T2 - T1.^2).^2 + 0.5*(T1 - 1).^2));
Z = Z ./ max(Z(:));

figure('Position',[100 100 400 300]);
hold on;
contour(T1, T2, Z, 12, 'k');
plot(traj(:,1), traj(:,2), '-ok', 'MarkerSize', 4, 'LineWidth', 1.2);

% label start and end directly on the figure (no legend)
text(traj(1,1)   + 0.2, traj(1,2)   + 1.5, ...
    'start', 'Interpreter','latex', 'FontSize', 14);
text(traj(end,1) + 0.2, traj(end,2) + 1.5, ...
    'end',   'Interpreter','latex', 'FontSize', 14);

hold off; box off;
xlabel('$\theta_1$', 'Interpreter', 'latex', 'FontSize', 14);
ylabel('$\theta_2$', 'Interpreter', 'latex', 'FontSize', 14);
