# hmc_traj.R
# Plots one leapfrog trajectory of the HMC sampler used in Example 6.5
# (see hmc_demo.R). The trajectory is generated by simulating L
# leapfrog steps with step size eps from a chosen starting point and
# deterministic momentum, then overlaid on the contours of the target
# density. The start and end points are labeled directly on the figure.
# The figure size and contour grid are matched to hmc_demo.R for
# visual consistency across the two panels of Figure 6.2.

# log target density and its gradient (same as hmc_demo.R)
logf <- function(q) -0.05*(q[2] - q[1]^2)^2 -
    0.5*(q[1] - 1)^2
grad_logf <- function(q) c(q[1]/5*(q[2] - q[1]^2) -
    (q[1] - 1), -(q[2] - q[1]^2)/10)

# trajectory settings: smaller step and longer chain than in hmc_demo
# are used here to produce a smoother visual path that traverses both
# sides of the high-density region
eps <- 0.3; L <- 20
theta0 <- c(-2, 6)                   # starting point above the high-density region
p0     <- c(1.5, -2)                 # momentum: rightward and downward

# simulate the trajectory, storing the position at every leapfrog step
traj <- matrix(0, L + 1, 2)
theta_t <- theta0; p_t <- p0
traj[1, ] <- theta_t
g <- grad_logf(theta_t)
p_t <- p_t + 0.5*eps*g
for (k in seq_len(L - 1)) {
    theta_t <- theta_t + eps*p_t
    g <- grad_logf(theta_t)
    p_t <- p_t + eps*g
    traj[k + 1, ] <- theta_t
}
theta_t <- theta_t + eps*p_t
traj[L + 1, ] <- theta_t

cat("trajectory start:", traj[1, ], " end:", round(traj[L + 1, ], 3), "\n")

# target density contours over a fixed range that approximates the
# typical sample range produced by hmc_demo.R, so that the contour
# lines line up visually across the two panels
xg <- seq(-2.5, 4.5, length.out = 300)
yg <- seq(-10, 19, length.out = 300)
# Z[i,j] = density at (xg[i], yg[j]) -- R's contour() takes the grid
# this way round rather than via meshgrid
Z <- outer(xg, yg, function(T1, T2)
    exp(-(0.05*(T2 - T1^2)^2 + 0.5*(T1 - 1)^2)))
Z <- Z/max(Z)

contour(xg, yg, Z, nlevels = 12, drawlabels = FALSE, col = "black",
        frame.plot = FALSE,
        xlab = expression(theta[1]), ylab = expression(theta[2]),
        cex.lab = 1.4)
lines(traj[, 1], traj[, 2], type = "o", pch = 1, cex = 0.7,
      lwd = 1.2, col = "black")

# label start and end directly on the figure (no legend)
text(traj[1, 1] + 0.2, traj[1, 2] + 1.5,
     "start", cex = 1.2, adj = 0)
text(traj[L + 1, 1] + 0.2, traj[L + 1, 2] + 1.5,
     "end", cex = 1.2, adj = 0)
